TEST_TO_SECTION_MAP = {

    # COMPLETE BLOOD COUNT
    "HAEMOGLOBIN(HB)": "COMPLETE BLOOD COUNT",
    "TOTAL COUNT": "COMPLETE BLOOD COUNT",
    "NEUTROPHILS": "COMPLETE BLOOD COUNT",
    "LYMPHOCYTES": "COMPLETE BLOOD COUNT",
    "MONOCYTES": "COMPLETE BLOOD COUNT",
    "EOSINOPHILS": "COMPLETE BLOOD COUNT",
    "BASOPHILS": "COMPLETE BLOOD COUNT",
    "PLATELET COUNT": "COMPLETE BLOOD COUNT",
    "PACKED CELL VOLUME ( PCV )": "COMPLETE BLOOD COUNT",
    "MPV": "COMPLETE BLOOD COUNT",
    "RBC COUNT": "COMPLETE BLOOD COUNT",
    "MCV": "COMPLETE BLOOD COUNT",
    "MCH": "COMPLETE BLOOD COUNT",
    "MCHC": "COMPLETE BLOOD COUNT",
    "RDW-CV": "COMPLETE BLOOD COUNT",

    # RFT - RENAL FUNCTION TEST
    "UREA": "RFT - RENAL FUNCTION TEST",
    "SERUM CREATININE": "RFT - RENAL FUNCTION TEST",
    "URIC ACID": "RFT - RENAL FUNCTION TEST",

    # ELECTROLYTES
    "SODIUM": "ELECTROLYTES",
    "POTASSIUM": "ELECTROLYTES",
    "CHLORIDE": "ELECTROLYTES",
    "RBS (RANDOM BLOOD SUGER)": "ELECTROLYTES",
    "PHOSPHORUS" : "ELECTROLYTES",

    # CRP QUANTITATIVE
    "CRP QUANTITATIVE": "CRP QUANTITATIVE",

    # TROPONIN
    "TROPONIN I[SERUM]": "TROPONIN I[SERUM]",

    # GLYCOSYLATED HAEMOGLOBIN
    "GLYCOSYLATED HAEMOGLOBIN": "GLYCOSYLATED HAEMOGLOBIN",

    # LIVER FUNCTION TEST
    "BILIRUBIN TOTAL": "LIVER FUNCTION TEST",
    "BILIRUBIN DIRECT": "LIVER FUNCTION TEST",
    "TOTAL PROTEINS": "LIVER FUNCTION TEST",
    "ALBUMIN": "LIVER FUNCTION TEST",
    "GLOBULIN": "LIVER FUNCTION TEST",
    "AST(SGOT)": "LIVER FUNCTION TEST",
    "ALT(SGPT)": "LIVER FUNCTION TEST",
    "ALKALINE PHOSPHATASE (ALP)": "LIVER FUNCTION TEST",

    # URINE ROUTINE (all subsections flattened)
    "VOLUME": "URINE ROUTINE",
    "pH": "URINE ROUTINE",
    "COLOUR": "URINE ROUTINE",
    "APPEARANCE": "URINE ROUTINE",
    "SPECIFIC GRAVITY": "URINE ROUTINE",
    "SUGAR": "URINE ROUTINE",
    "RBCs": "URINE ROUTINE",
    "PUS CELLS": "URINE ROUTINE",
    "EPITHELIAL": "URINE ROUTINE",
    "CASTS": "URINE ROUTINE",
    "CRYSTALS": "URINE ROUTINE",
    "OTHERS": "URINE ROUTINE",

    # ARTERIAL BLOOD GAS ANALYSIS
    "pH (BLOOD)": "ARTERIAL BLOOD GAS ANALYSIS",
    "pCO2": "ARTERIAL BLOOD GAS ANALYSIS",
    "pO2": "ARTERIAL BLOOD GAS ANALYSIS",
    "HCO3": "ARTERIAL BLOOD GAS ANALYSIS",
    "Hb": "ARTERIAL BLOOD GAS ANALYSIS",
    "SO2": "ARTERIAL BLOOD GAS ANALYSIS"
}
